import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function paintLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="bg-black h-[50px] relative">
        <nav className="flex h-full p-1 justify-between mx-auto md:w-9/12 lg:w-8/12 items-center">
          <div>
            <Link href="/paint">Paint App</Link>
          </div>
          <ul className="flex items-center">
            <button>Apps</button>
            <li>
              <Link href="/account">Account</Link>
            </li>
          </ul>
        </nav>
      </div>
      {children}
    </div>
  );
}
